test_xdmf_grid – XH5For
test_xdmf_grid Program
52 statements
Source File
Uses:
fox_xdmf
fox_dom
Calls
Variables
file grid document_root element element_list i
Source Code
test_xdmf_grid
Variables
Type Attributes Name Initial
type(xdmf_file_t) :: file
type(xdmf_grid_t) :: grid
type(Node), pointer :: document_root
type(Node), pointer :: element
type(NodeList), pointer :: element_list
integer :: i
Source Code
program test_xdmf_grid
use fox_xdmf
use fox_dom
implicit none
    type(xdmf_file_t) :: file
    type(xdmf_grid_t) :: grid
    type(Node), pointer :: document_root, element
    type(NodeList), pointer :: element_list
    integer :: i
    call file%set_filename('test_xdmf_grid.xmf')
    call file%openfile()
    call grid%open(file%xml_handler); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, Name='GridName'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, GridType='Uniform'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, GridType='Collection'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, GridType='Tree'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, GridType='Subset')
    call grid%open(file%xml_handler, GridType='Unknown')
    call grid%open(file%xml_handler, CollectionType='Spatial'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, CollectionType='Temporal'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, CollectionType='Unknown')
    call grid%open(file%xml_handler, Section='DataItem'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, Section='All'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, Section='Unknown'); call grid%close(file%xml_handler)
    call grid%open(file%xml_handler, Name='GridName', GridType='Collection', CollectionType='Spatial',Section='DataItem'); call grid%close(file%xml_handler)
    call grid%close(file%xml_handler)
    call grid%close(file%xml_handler)
    call grid%close(file%xml_handler)
    call file%closefile()
    call file%parsefile()
    document_root => getDocumentElement(file%get_document_root())
    if(hasChildNodes(document_root)) then
        element_list => getElementsByTagname(document_root, 'Grid')
        do i = 0, getLength(element_list) - 1
            element => item(element_list, i)
            call grid%parse(element)
            call grid%print()
        enddo
    endif
    call grid%free()
end program test_xdmf_grid
All Programs
ch_unstructured_hexahedron steps_handler_test test_hdf5_hyperslabs_handler test_hdf5_rect_dpp_handler test_hdf5_rect_hyperslabs_handler test_hdf5_reg_dpp_handler test_hdf5_reg_hyperslabs_handler test_hdf5_uns_hyperslabs_handler test_mpi_environment test_xdmf_attribute test_xdmf_character_data test_xdmf_dataitem test_xdmf_geometry test_xdmf_grid test_xdmf_rect_dpp_handler test_xdmf_rect_hyperslabs_handler test_xdmf_reg_ddp_handler test_xdmf_reg_hyperslabs_handler test_xdmf_time test_xdmf_topology test_xdmf_uns_ddp_handler test_xdmf_uns_hyperslabs_handler test_xdmf_xinclude try_compile_hdf5_mod try_compile_mpi_mod wxml_example xh5for_ch_rectilinear_grid xh5for_ch_rectilinear_grid xh5for_ch_rectilinear_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_unstructured_hexahedron xh5for_ch_unstructured_hexahedron xh5for_ch_unstructured_mixedtopology xh5for_ch_unstructured_mixedtopology xh5for_ch_unstructured_quadrilateral xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_triangles xh5for_dpp_rectilinear_grid xh5for_dpp_rectilinear_grid xh5for_dpp_rectilinear_grid xh5for_dpp_regular_grid xh5for_dpp_unstructured_hexahedron xh5for_dpp_unstructured_mixedtopology xh5for_dpp_unstructured_quadrilateral xh5for_dpp_unstructured_tetrahedron xh5for_dpp_unstructured_triangles
Call graph
test_xdmf_grid calls item, getdocumentelement, haschildnodes, getlength, getelementsbytagname