test_xdmf_time – XH5For
test_xdmf_time Program
45 statements
Source File
Uses:
fox_xdmf
fox_dom
PENF
Calls
Variables
file time document_root element element_list i
Source Code
test_xdmf_time
Variables
Type Attributes Name Initial
type(xdmf_file_t) :: file
type(xdmf_time_t) :: time
type(Node), pointer :: document_root
type(Node), pointer :: element
type(NodeList), pointer :: element_list
integer :: i
Source Code
program test_xdmf_time
use fox_xdmf
use fox_dom
use PENF, only: R4P, R8P
implicit none
    type(xdmf_file_t) :: file
    type(xdmf_time_t) :: time
    type(Node), pointer :: document_root, element
    type(NodeList), pointer :: element_list
    integer :: i
    call file%set_filename('test_xdmf_time.xmf')
    call file%openfile()
    call time%open(file%xml_handler); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='Single'); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='HyperSlab'); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='List'); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='list'); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='Range'); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='Unknown'); call time%close(file%xml_handler)
    call time%open(file%xml_handler, Value=1._R4P); call time%close(file%xml_handler)
    call time%open(file%xml_handler, Value=1._R8P); call time%close(file%xml_handler)
    call time%open(file%xml_handler, TimeType='Single', Value=1._R4P); call time%close(file%xml_handler)
    call file%closefile()
    call file%parsefile()
    document_root => getDocumentElement(file%get_document_root())
    if(hasChildNodes(document_root)) then
        element_list => getElementsByTagname(document_root, 'Time')
        do i = 0, getLength(element_list) - 1
            element => item(element_list, i)
            call time%parse(element)
            call time%print()
        enddo
    endif
    call time%free()
end program test_xdmf_time
All Programs
ch_unstructured_hexahedron steps_handler_test test_hdf5_hyperslabs_handler test_hdf5_rect_dpp_handler test_hdf5_rect_hyperslabs_handler test_hdf5_reg_dpp_handler test_hdf5_reg_hyperslabs_handler test_hdf5_uns_hyperslabs_handler test_mpi_environment test_xdmf_attribute test_xdmf_character_data test_xdmf_dataitem test_xdmf_geometry test_xdmf_grid test_xdmf_rect_dpp_handler test_xdmf_rect_hyperslabs_handler test_xdmf_reg_ddp_handler test_xdmf_reg_hyperslabs_handler test_xdmf_time test_xdmf_topology test_xdmf_uns_ddp_handler test_xdmf_uns_hyperslabs_handler test_xdmf_xinclude try_compile_hdf5_mod try_compile_mpi_mod wxml_example xh5for_ch_rectilinear_grid xh5for_ch_rectilinear_grid xh5for_ch_rectilinear_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_unstructured_hexahedron xh5for_ch_unstructured_hexahedron xh5for_ch_unstructured_mixedtopology xh5for_ch_unstructured_mixedtopology xh5for_ch_unstructured_quadrilateral xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_triangles xh5for_dpp_rectilinear_grid xh5for_dpp_rectilinear_grid xh5for_dpp_rectilinear_grid xh5for_dpp_regular_grid xh5for_dpp_unstructured_hexahedron xh5for_dpp_unstructured_mixedtopology xh5for_dpp_unstructured_quadrilateral xh5for_dpp_unstructured_tetrahedron xh5for_dpp_unstructured_triangles
Call graph
test_xdmf_time calls item, getdocumentelement, haschildnodes, getlength, getelementsbytagname