test_xdmf_xinclude – XH5For
test_xdmf_xinclude Program
30 statements
Source File
Uses:
fox_xdmf
fox_dom
Calls
Variables
file xinclude document_root element element_list i
Source Code
test_xdmf_xinclude
Variables
Type Attributes Name Initial
type(xdmf_file_t) :: file
type(xdmf_xinclude_t) :: xinclude
type(Node), pointer :: document_root
type(Node), pointer :: element
type(NodeList), pointer :: element_list
integer :: i
Source Code
program test_xdmf_xinclude
use fox_xdmf
use fox_dom
implicit none
    type(xdmf_file_t) :: file
    type(xdmf_xinclude_t) :: xinclude
    type(Node), pointer :: document_root, element
    type(NodeList), pointer :: element_list
    integer :: i
    call file%set_filename('test_xdmf_xinclude.xmf')
    call file%openfile()
    call xinclude%open(file%xml_handler); call xinclude%close(file%xml_handler)
    call xinclude%open(file%xml_handler, href="http://url"); call xinclude%close(file%xml_handler)
    call xinclude%open(file%xml_handler, href="localfile.xmf"); call xinclude%close(file%xml_handler)
    call file%closefile()
    call file%parsefile()
    document_root => getDocumentElement(file%get_document_root())
    if(hasChildNodes(document_root)) then
        element_list => getElementsByTagname(document_root, 'xi:include')
        do i = 0, getLength(element_list) - 1
            element => item(element_list, i)
            call xinclude%parse(element)
            call xinclude%print()
        enddo
    endif
    call xinclude%free()
end program test_xdmf_xinclude
All Programs
ch_unstructured_hexahedron steps_handler_test test_hdf5_hyperslabs_handler test_hdf5_rect_dpp_handler test_hdf5_rect_hyperslabs_handler test_hdf5_reg_dpp_handler test_hdf5_reg_hyperslabs_handler test_hdf5_uns_hyperslabs_handler test_mpi_environment test_xdmf_attribute test_xdmf_character_data test_xdmf_dataitem test_xdmf_geometry test_xdmf_grid test_xdmf_rect_dpp_handler test_xdmf_rect_hyperslabs_handler test_xdmf_reg_ddp_handler test_xdmf_reg_hyperslabs_handler test_xdmf_time test_xdmf_topology test_xdmf_uns_ddp_handler test_xdmf_uns_hyperslabs_handler test_xdmf_xinclude try_compile_hdf5_mod try_compile_mpi_mod wxml_example xh5for_ch_rectilinear_grid xh5for_ch_rectilinear_grid xh5for_ch_rectilinear_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_regular_grid xh5for_ch_unstructured_hexahedron xh5for_ch_unstructured_hexahedron xh5for_ch_unstructured_mixedtopology xh5for_ch_unstructured_mixedtopology xh5for_ch_unstructured_quadrilateral xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_tetrahedron xh5for_ch_unstructured_triangles xh5for_dpp_rectilinear_grid xh5for_dpp_rectilinear_grid xh5for_dpp_rectilinear_grid xh5for_dpp_regular_grid xh5for_dpp_unstructured_hexahedron xh5for_dpp_unstructured_mixedtopology xh5for_dpp_unstructured_quadrilateral xh5for_dpp_unstructured_tetrahedron xh5for_dpp_unstructured_triangles
Call graph
test_xdmf_xinclude calls getlength, getelementsbytagname, getdocumentelement, item, haschildnodes