is_in_option_list – XH5For
is_in_option_list Function
11 statements
Source File
public elemental function is_in_option_list(option_list, option, separator)
Return True if option is a substring of option_list option_list is a string composed by options delimited by separators.
Note
Case sensitive
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: option_list
List of allowed options
character(len=*), intent(in) :: option
Option to search
character(len=*), intent(in), optional :: separator
Separator between options
Return Value logical
Option founded flag
Called By
Source Code
is_in_option_list
Source Code
    elemental function is_in_option_list(option_list, option, separator)
    !-----------------------------------------------------------------
    !< Return True if *option* is a substring of *option_list*
    !< *option_list* is a string composed by options delimited
    !< by separators.
    !< @Note Case sensitive
    !-----------------------------------------------------------------
        character(len=*),           intent(IN) :: option_list         !< List of allowed options
        character(len=*),           intent(IN) :: option              !< Option to search
        character(len=*), optional, intent(IN) :: separator           !< Separator between options
        logical                                :: is_in_option_list   !< Option founded flag
        character(len=:), allocatable          :: sep                 !< Aux separator variable
    !-----------------------------------------------------------------
        sep = ' '; if(present(separator)) sep = separator
        is_in_option_list = .false.
        if(INDEX(adjustl(trim(option)), adjustl(trim(sep))) == 0) &
            is_in_option_list = INDEX(option_list, adjustl(trim(option))) > 0
    end function is_in_option_list
All Procedures
Abort Count_tokens generate_hexa_mesh generate_hexa_mesh GetNumberOfComponentsFromAttributeType GetNumberOfNodesPerElement GetSpaceDimension GetXDMFAttributeTypeName GetXDMFCenterTypeFromName GetXDMFCenterTypeName GetXDMFGeometryTypeFromName GetXDMFGeometryTypeName GetXDMFTopologyTypeFromName GetXDMFTopologyTypeName is_in_option_list isSupportedAttributeCenterName isSupportedAttributeTypeNAme isSupportedDataItemFormatName isSupportedDataItemNumberTypeName isSupportedDataItemPrecision isSupportedDataItemTypeName isSupportedGeometryType isSupportedGridCollectionTypeName isSupportedGridSectionName isSupportedGridType isSupportedGridTypeName isSupportedStrategy isSupportedTimeTypeName isSupportedTopologyType isSupportedTopologyTypeName MkdirFullPath Next_token Upper_Case warning_message Wtime
Call graph
issupportedattributetypename calls is_in_option_list
issupportedtopologytypename calls is_in_option_list
issupportedgridsectionname calls is_in_option_list
issupporteddataitemformatname calls is_in_option_list
issupportedgridtypename calls is_in_option_list
issupporteddataitemtypename calls is_in_option_list
issupportedattributecentername calls is_in_option_list
issupportedtimetypename calls is_in_option_list
issupporteddataitemnumbertypename calls is_in_option_list
issupportedgridcollectiontypename calls is_in_option_list